### ISSUE TITLE
failed to build on windows 10

### ISSUE THREAD

**Issue by laoshaw** [EstebanBorai/http-server#168]
it's built on linux just fine, but very hard to cross compile for windows from Linux, so I just installed rust on windows and start building, then it failed:

```
   Compiling http-server v0.7.4 (C:\Users\Test\rust\http-server)
error[E0515]: cannot return value referencing local variable `bytes`
  --> src\utils\url_encode.rs:50:13
   |
39 |                             &bytes
   |                             ------ `bytes` is borrowed here
...
50 |             std::iter::once("/").chain(segment)
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ returns a value referencing data owned by the current function
   |
   = help: use `.collect()` to allocate the iterator

For more information about this error, try `rustc --explain E0515`.
error: could not compile `http-server` due to previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by LeoBorai** [comment]
Hi @laoshaw, thanks for opening this issue!

Yeah, I must confess that I acknowledge the issue, a fix for windows is on the works and I'm planning to deliver it in the next hours. I'm apologize for any issues this could be causing for you.

This regression bug was introduced on #164. Are you experiencing any issues related to this?

**Comment by laoshaw** [comment]
Thanks for the response, will wait for its fix.

**Comment by LeoBorai** [comment]
Hi @laoshaw! Support for UTF-8 percent encoding has landed for both Windows and Unix based systems.

The build on Windows is back working as expected.

Is important to note that support for non UTF-8 encoding is still on the works.

Thanks for your interest!
